#pragma kernel Impulse

float source_amount;
float radius;
float dt;
float2 source_pos;
float2 size;

RWTexture2D<float> write_R;
Texture2D<float> read_R;


[numthreads(8,8,1)]
void Impulse (uint3 id : SV_DispatchThreadID)
{
	float2 pos = id / (size.xy - 1.0f) - source_pos.xy;
	float magnitude = pos.x * pos.x + pos.y * pos.y;
	float radius_squared = radius * radius;

	float amount = exp(-magnitude/radius_squared) * source_amount * dt;
	write_R[id.xy] = read_R[id.xy] + amount;
}
