#pragma kernel ApplyParticlesVelocities

float dt;
int num_particles;

struct FuelParticle//CPU struct maps to this one
{
	float3 position;
	float3 velocity;
	float temperature;
	float mass;
	float soot_accumulation;
};

RWStructuredBuffer<FuelParticle> particles;


[numthreads(8,1,1)]
void ApplyParticlesVelocities (uint3 id : SV_DispatchThreadID)
{
	float3 velocity = particles[id.x].velocity;	
	particles[id.x].position += velocity * dt;
}
