#define THREAD_COUNT = 8;

float dt;
float dissipation;
float decay;
float forward;
float4 size;

RWTexture2D<float2> velocity;
RWTexture2D<float2> obstacles;

RWTexture2D<float2> write;
RWTexture2D<float2> read;


float2 GetAdvectedPosition(float2 _position, uint3 id)
{
	_position -= dt * forward * velocity[id.xy];
	return _position;
}

#pragma kernel AdvectVelocity
[numthreads(THREAD_COUNT, THREAD_COUNT, 1)]
void AdvectVelocity(uint3 id : SV_DispatchThreadID)
{

}


#pragma kernel Advect
[numthreads(THREAD_COUNT, THREAD_COUNT, 1)]
void Advect(uint3 id : SV_DispatchThreadID)
{
	
}
