#pragma kernel Boundary

RWTexture2D<float> write_R;
float2 inverse_size;

[numthreads(8,8,1)]
void Boundary (uint3 id : SV_DispatchThreadID)
{
	float obstacle = 0;

	//if at edge add an obstacle
	if (id.x <= inverse_size.x)	{ obstacle = 1;	}
	if (id.x >= 1.0f - inverse_size.x)	{ obstacle = 1;	}
	if (id.y <= inverse_size.y)	{ obstacle = 1;	}
	if (id.y >= 1.0f - inverse_size.y)	{ obstacle = 1;	}

	write_R[id.xy] = obstacle;
}
